name: super_extensions
description: "A Flutter package that provides various useful extensions for different data types in Dart and Flutter."
version: 1.2.3
homepage: ''

environment:
  sdk: ">=3.5.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
